#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o phyluce_raxml1.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N phyluce_raxml1
#PBS -A hpc_herp01
#PBS -e phyluce_raxml1.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/matched_contigs/taxon-set600/
cd $WORK_DIR

/home/cenewman/anaconda/bin/phyluce_align_format_nexus_files_for_raxml --alignments mafft-nexus-50/ --output raxml-50

date

exit 0
