#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o raxml_MLboot.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N raxml_MLboot
#PBS -A hpc_herp01
#PBS -e raxml_MLboot.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/raxml/
cd $WORK_DIR

raxmlHPC-PTHREADS-SSE3 -s mafft-85-raxml.phylip -n raxml-85_boot -b 92875 -# 1000 -m GTRGAMMA -T 16

date

exit 0