#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=50:00:00
#PBS -o raxml_80_all_rboot1000_final.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N rax80_all_1kf
#PBS -A hpc_skink01
#PBS -e raxml_80_all_rboot1000_final.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/raxml/final
cd $WORK_DIR

raxmlHPC-PTHREADS-SSE3 -s mafft-nexus-80-all.phylip -n all-80p-rboot-1000 -f a -x 345878 -# 100 -p 834154 -m GTRGAMMA -T 16

date

exit 0
