#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o raxml_60_all_draw_final.out
#PBS -M cnewm15@lsu.edu
#PBS -m ae
#PBS -N rax60_all_1kf
#PBS -A hpc_skink01
#PBS -e raxml_60_all_draw_final.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/raxml/final
cd $WORK_DIR

raxmlHPC-PTHREADS-SSE3 -f b -t RAxML_result.all-60p-ML-1000 -z RAxML_bootstrap.all-60p-rboot-1000 -n all-60p-draw-1000 -m GTRGAMMA -T 16

date

exit 0
