#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o raxml_mito_rboot1000.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N raxml_mt
#PBS -A hpc_skink01
#PBS -e raxml_mito_rboot1000.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/raxml/mito
cd $WORK_DIR

raxmlHPC-PTHREADS-SSE3 -s CytbMVZ_updated_UCE.phylip -n mt_rapidboot_1000 -f a -x 134057 -# 1000 -p 617023 -m GTRGAMMA -T 16

date

exit 0
