#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=50:00:00
#PBS -o raxml_80_1k_rboot1000_final.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N rax80_1k_1kf
#PBS -A hpc_skink01
#PBS -e raxml_80_1k_rboot1000_final.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/raxml/final
cd $WORK_DIR

raxmlHPC-PTHREADS-SSE3 -s mafft-nexus-80-1k.phylip -n 80_1k_rapidboot_1000 -f a -x 7643516 -# 1000 -p 657868 -m GTRGAMMA -T 16

date

exit 0
