#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=12:00:00
#PBS -o picard_dict.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N picard_dict
#PBS -A hpc_herp01
#PBS -e picard_dict.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -Xmx2g -jar ~/anaconda/pkgs/picard-1.106-0/jar/CreateSequenceDictionary.jar R=popgen/cen131.fasta O=popgen/cen131.dict

date

exit 0