#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=36:00:00
#PBS -o gatk_call_snp.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N gatk_callsnp
#PBS -A hpc_herp01
#PBS -e gatk_call_snp.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -Xmx2g -jar ~/programs/GenomeAnalysisTK.jar -T UnifiedGenotyper -R popgen/cen131.fasta -I popgen/8_gatk/Pserratus_RI.bam -gt_mode DISCOVERY -o popgen/8_gatk/Pserratus_raw_SNPs.vcf -ploidy 2 -rf BadCigar

date

exit 0