#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=36:00:00
#PBS -o gatk_annotate_snp.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N gatk_annSnp
#PBS -A hpc_herp01
#PBS -e gatk_annotate_snp.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -Xmx2g -jar ~/programs/GenomeAnalysisTK.jar -T VariantAnnotator -R popgen/cen131.fasta -I popgen/8_gatk/Pserratus_RI.bam -G StandardAnnotation -V:variant,VCF popgen/8_gatk/Pserratus_raw_SNPs.vcf -XA SnpEff -o popgen/8_gatk/Pserratus_SNPs_annotated.vcf -rf BadCigar

date

exit 0