#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=36:00:00
#PBS -o collateseqs.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N collateseqs
#PBS -A hpc_herp01
#PBS -e collateseqs.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

python $HOME_DIR/programs/collate_sample_fastas_GATK.py popgen/10_sequences/ popgen/11_fasta-parts sequences.txt

date

exit 0