#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o bwa_aln3.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N bwa_aln3
#PBS -A hpc_herp01
#PBS -e bwa_aln3.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT142/split-adapter-quality-trimmed/Pserratus_BDT142-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT142_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT142/split-adapter-quality-trimmed/Pserratus_BDT142-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT142_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT145/split-adapter-quality-trimmed/Pserratus_BDT145-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT145_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT145/split-adapter-quality-trimmed/Pserratus_BDT145-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT145_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT148/split-adapter-quality-trimmed/Pserratus_BDT148-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT148_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT148/split-adapter-quality-trimmed/Pserratus_BDT148-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT148_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT149/split-adapter-quality-trimmed/Pserratus_BDT149-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT149_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT149/split-adapter-quality-trimmed/Pserratus_BDT149-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT149_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT153/split-adapter-quality-trimmed/Pserratus_BDT153-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT153_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT153/split-adapter-quality-trimmed/Pserratus_BDT153-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT153_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT157/split-adapter-quality-trimmed/Pserratus_BDT157-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT157_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT157/split-adapter-quality-trimmed/Pserratus_BDT157-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT157_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT161/split-adapter-quality-trimmed/Pserratus_BDT161-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT161_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT161/split-adapter-quality-trimmed/Pserratus_BDT161-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT161_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT163/split-adapter-quality-trimmed/Pserratus_BDT163-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT163_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT163/split-adapter-quality-trimmed/Pserratus_BDT163-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT163_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT164/split-adapter-quality-trimmed/Pserratus_BDT164-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT164_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT164/split-adapter-quality-trimmed/Pserratus_BDT164-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT164_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT166/split-adapter-quality-trimmed/Pserratus_BDT166-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT166_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT166/split-adapter-quality-trimmed/Pserratus_BDT166-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT166_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT168/split-adapter-quality-trimmed/Pserratus_BDT168-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT168_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT168/split-adapter-quality-trimmed/Pserratus_BDT168-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT168_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT169/split-adapter-quality-trimmed/Pserratus_BDT169-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT169_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT169/split-adapter-quality-trimmed/Pserratus_BDT169-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT169_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT173/split-adapter-quality-trimmed/Pserratus_BDT173-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT173_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT173/split-adapter-quality-trimmed/Pserratus_BDT173-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT173_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT174/split-adapter-quality-trimmed/Pserratus_BDT174-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT174_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT174/split-adapter-quality-trimmed/Pserratus_BDT174-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT174_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT175/split-adapter-quality-trimmed/Pserratus_BDT175-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT175_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT175/split-adapter-quality-trimmed/Pserratus_BDT175-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT175_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT177/split-adapter-quality-trimmed/Pserratus_BDT177-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT177_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT177/split-adapter-quality-trimmed/Pserratus_BDT177-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT177_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT178/split-adapter-quality-trimmed/Pserratus_BDT178-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT178_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT178/split-adapter-quality-trimmed/Pserratus_BDT178-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT178_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT179/split-adapter-quality-trimmed/Pserratus_BDT179-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT179_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT179/split-adapter-quality-trimmed/Pserratus_BDT179-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT179_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT180/split-adapter-quality-trimmed/Pserratus_BDT180-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT180_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT180/split-adapter-quality-trimmed/Pserratus_BDT180-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT180_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT181/split-adapter-quality-trimmed/Pserratus_BDT181-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT181_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT181/split-adapter-quality-trimmed/Pserratus_BDT181-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT181_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_CEN131/split-adapter-quality-trimmed/Pserratus_CEN131-READ1.fastq.gz > popgen/5-mapping/Pserratus_CEN131_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_CEN131/split-adapter-quality-trimmed/Pserratus_CEN131-READ2.fastq.gz > popgen/5-mapping/Pserratus_CEN131_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_CEN1312/split-adapter-quality-trimmed/Pserratus_CEN1312-READ1.fastq.gz > popgen/5-mapping/Pserratus_CEN1312_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_CEN1312/split-adapter-quality-trimmed/Pserratus_CEN1312-READ2.fastq.gz > popgen/5-mapping/Pserratus_CEN1312_read2.sa.sai

date

exit 0