#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o bwa_aln1.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N bwa_aln1
#PBS -A hpc_herp01
#PBS -e bwa_aln1.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pcinereus_LSUMZ15568/split-adapter-quality-trimmed/Pcinereus_LSUMZ15568-READ1.fastq.gz > popgen/5-mapping/Pcinereus_LSUMZ15568_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pcinereus_LSUMZ15568/split-adapter-quality-trimmed/Pcinereus_LSUMZ15568-READ2.fastq.gz > popgen/5-mapping/Pcinereus_LSUMZ15568_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pcinereus_LSUMZ15569/split-adapter-quality-trimmed/Pcinereus_LSUMZ15569-READ1.fastq.gz > popgen/5-mapping/Pcinereus_LSUMZ15569_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pcinereus_LSUMZ15569/split-adapter-quality-trimmed/Pcinereus_LSUMZ15569-READ2.fastq.gz > popgen/5-mapping/Pcinereus_LSUMZ15569_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT041/split-adapter-quality-trimmed/Pserratus_BDT041-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT041_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT041/split-adapter-quality-trimmed/Pserratus_BDT041-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT041_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT042/split-adapter-quality-trimmed/Pserratus_BDT042-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT042_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT042/split-adapter-quality-trimmed/Pserratus_BDT042-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT042_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT044/split-adapter-quality-trimmed/Pserratus_BDT044-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT044_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT044/split-adapter-quality-trimmed/Pserratus_BDT044-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT044_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT051/split-adapter-quality-trimmed/Pserratus_BDT051-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT051_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT051/split-adapter-quality-trimmed/Pserratus_BDT051-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT051_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT054/split-adapter-quality-trimmed/Pserratus_BDT054-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT054_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT054/split-adapter-quality-trimmed/Pserratus_BDT054-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT054_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT057/split-adapter-quality-trimmed/Pserratus_BDT057-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT057_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT057/split-adapter-quality-trimmed/Pserratus_BDT057-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT057_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT058/split-adapter-quality-trimmed/Pserratus_BDT058-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT058_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT058/split-adapter-quality-trimmed/Pserratus_BDT058-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT058_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT060/split-adapter-quality-trimmed/Pserratus_BDT060-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT060_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT060/split-adapter-quality-trimmed/Pserratus_BDT060-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT060_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT062/split-adapter-quality-trimmed/Pserratus_BDT062-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT062_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT062/split-adapter-quality-trimmed/Pserratus_BDT062-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT062_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT063/split-adapter-quality-trimmed/Pserratus_BDT063-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT063_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT063/split-adapter-quality-trimmed/Pserratus_BDT063-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT063_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT064/split-adapter-quality-trimmed/Pserratus_BDT064-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT064_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT064/split-adapter-quality-trimmed/Pserratus_BDT064-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT064_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT075/split-adapter-quality-trimmed/Pserratus_BDT075-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT075_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT075/split-adapter-quality-trimmed/Pserratus_BDT075-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT075_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT076/split-adapter-quality-trimmed/Pserratus_BDT076-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT076_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT076/split-adapter-quality-trimmed/Pserratus_BDT076-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT076_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT077/split-adapter-quality-trimmed/Pserratus_BDT077-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT077_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT077/split-adapter-quality-trimmed/Pserratus_BDT077-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT077_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT079/split-adapter-quality-trimmed/Pserratus_BDT079-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT079_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT079/split-adapter-quality-trimmed/Pserratus_BDT079-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT079_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT080/split-adapter-quality-trimmed/Pserratus_BDT080-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT080_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT080/split-adapter-quality-trimmed/Pserratus_BDT080-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT080_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT081/split-adapter-quality-trimmed/Pserratus_BDT081-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT081_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT081/split-adapter-quality-trimmed/Pserratus_BDT081-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT081_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT082/split-adapter-quality-trimmed/Pserratus_BDT082-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT082_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT082/split-adapter-quality-trimmed/Pserratus_BDT082-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT082_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT083/split-adapter-quality-trimmed/Pserratus_BDT083-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT083_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT083/split-adapter-quality-trimmed/Pserratus_BDT083-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT083_read2.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT084/split-adapter-quality-trimmed/Pserratus_BDT084-READ1.fastq.gz > popgen/5-mapping/Pserratus_BDT084_read1.sa.sai
bwa aln popgen/cen131.fasta cleaned_reads_from_illumiprocessor/Pserratus_BDT084/split-adapter-quality-trimmed/Pserratus_BDT084-READ2.fastq.gz > popgen/5-mapping/Pserratus_BDT084_read2.sa.sai

date

exit 0