#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=12:00:00
#PBS -o samtools4.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N samtools4
#PBS -A hpc_herp01
#PBS -e samtools4.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

samtools view -bS popgen/5-mapping/Pserratus_BDT178-aln.sam > popgen/5-mapping/Pserratus_BDT178-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_BDT179-aln.sam > popgen/5-mapping/Pserratus_BDT179-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_BDT180-aln.sam > popgen/5-mapping/Pserratus_BDT180-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_BDT181-aln.sam > popgen/5-mapping/Pserratus_BDT181-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN131-aln.sam > popgen/5-mapping/Pserratus_CEN131-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN1312-aln.sam > popgen/5-mapping/Pserratus_CEN1312-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN132-aln.sam > popgen/5-mapping/Pserratus_CEN132-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN134-aln.sam > popgen/5-mapping/Pserratus_CEN134-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN136-aln.sam > popgen/5-mapping/Pserratus_CEN136-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN139-aln.sam > popgen/5-mapping/Pserratus_CEN139-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_CEN142-aln.sam > popgen/5-mapping/Pserratus_CEN142-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_ENR0165-aln.sam > popgen/5-mapping/Pserratus_ENR0165-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_FHSM15253-aln.sam > popgen/5-mapping/Pserratus_FHSM15253-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_FHSM15535-aln.sam > popgen/5-mapping/Pserratus_FHSM15535-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_FHSM15547-aln.sam > popgen/5-mapping/Pserratus_FHSM15547-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_FHSM15548-aln.sam > popgen/5-mapping/Pserratus_FHSM15548-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_FHSM15549-aln.sam > popgen/5-mapping/Pserratus_FHSM15549-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ18827-aln.sam > popgen/5-mapping/Pserratus_LSUMZ18827-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ18828-aln.sam > popgen/5-mapping/Pserratus_LSUMZ18828-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ21037-aln.sam > popgen/5-mapping/Pserratus_LSUMZ21037-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ21256-aln.sam > popgen/5-mapping/Pserratus_LSUMZ21256-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ2558-aln.sam > popgen/5-mapping/Pserratus_LSUMZ2558-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ2568-aln.sam > popgen/5-mapping/Pserratus_LSUMZ2568-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_LSUMZ2569-aln.sam > popgen/5-mapping/Pserratus_LSUMZ2569-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_MVZ145058-aln.sam > popgen/5-mapping/Pserratus_MVZ145058-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_MVZ145059-aln.sam > popgen/5-mapping/Pserratus_MVZ145059-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_OMNH40315-aln.sam > popgen/5-mapping/Pserratus_OMNH40315-aln.bam
samtools view -bS popgen/5-mapping/Pserratus_OMNH41642-aln.sam > popgen/5-mapping/Pserratus_OMNH41642-aln.bam

date

exit 0