#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=12:00:00
#PBS -o picard_clean3.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N picard_clean3
#PBS -A hpc_herp01
#PBS -e picard_clean3.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT139-aln.bam O=popgen/6_picard/Pserratus_BDT139-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT142-aln.bam O=popgen/6_picard/Pserratus_BDT142-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT145-aln.bam O=popgen/6_picard/Pserratus_BDT145-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT148-aln.bam O=popgen/6_picard/Pserratus_BDT148-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT149-aln.bam O=popgen/6_picard/Pserratus_BDT149-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT153-aln.bam O=popgen/6_picard/Pserratus_BDT153-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT157-aln.bam O=popgen/6_picard/Pserratus_BDT157-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT161-aln.bam O=popgen/6_picard/Pserratus_BDT161-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT163-aln.bam O=popgen/6_picard/Pserratus_BDT163-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT164-aln.bam O=popgen/6_picard/Pserratus_BDT164-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT166-aln.bam O=popgen/6_picard/Pserratus_BDT166-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT168-aln.bam O=popgen/6_picard/Pserratus_BDT168-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT169-aln.bam O=popgen/6_picard/Pserratus_BDT169-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT173-aln.bam O=popgen/6_picard/Pserratus_BDT173-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT174-aln.bam O=popgen/6_picard/Pserratus_BDT174-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT175-aln.bam O=popgen/6_picard/Pserratus_BDT175-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT177-aln.bam O=popgen/6_picard/Pserratus_BDT177-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT178-aln.bam O=popgen/6_picard/Pserratus_BDT178-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT179-aln.bam O=popgen/6_picard/Pserratus_BDT179-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT180-aln.bam O=popgen/6_picard/Pserratus_BDT180-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT181-aln.bam O=popgen/6_picard/Pserratus_BDT181-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_CEN131-aln.bam O=popgen/6_picard/Pserratus_CEN131-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_CEN1312-aln.bam O=popgen/6_picard/Pserratus_CEN1312-aln_CL.bam VALIDATION_STRINGENCY=SILENT

date

exit 0