#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=12:00:00
#PBS -o picard_clean2.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N picard_clean2
#PBS -A hpc_herp01
#PBS -e picard_clean2.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT084-aln.bam O=popgen/6_picard/Pserratus_BDT084-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT085-aln.bam O=popgen/6_picard/Pserratus_BDT085-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT087-aln.bam O=popgen/6_picard/Pserratus_BDT087-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT089-aln.bam O=popgen/6_picard/Pserratus_BDT089-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT092-aln.bam O=popgen/6_picard/Pserratus_BDT092-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT093-aln.bam O=popgen/6_picard/Pserratus_BDT093-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT094-aln.bam O=popgen/6_picard/Pserratus_BDT094-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT095-aln.bam O=popgen/6_picard/Pserratus_BDT095-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT098-aln.bam O=popgen/6_picard/Pserratus_BDT098-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT100-aln.bam O=popgen/6_picard/Pserratus_BDT100-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT101-aln.bam O=popgen/6_picard/Pserratus_BDT101-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT103-aln.bam O=popgen/6_picard/Pserratus_BDT103-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT109-aln.bam O=popgen/6_picard/Pserratus_BDT109-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT111-aln.bam O=popgen/6_picard/Pserratus_BDT111-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT113-aln.bam O=popgen/6_picard/Pserratus_BDT113-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT114-aln.bam O=popgen/6_picard/Pserratus_BDT114-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT118-aln.bam O=popgen/6_picard/Pserratus_BDT118-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT123-aln.bam O=popgen/6_picard/Pserratus_BDT123-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT132-aln.bam O=popgen/6_picard/Pserratus_BDT132-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT134-aln.bam O=popgen/6_picard/Pserratus_BDT134-aln_CL.bam VALIDATION_STRINGENCY=SILENT
java -jar ~/anaconda/jar/CleanSam.jar I=popgen/5-mapping/Pserratus_BDT135-aln.bam O=popgen/6_picard/Pserratus_BDT135-aln_CL.bam VALIDATION_STRINGENCY=SILENT

date

exit 0