#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=12:00:00
#PBS -o picard_mark4.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N picard_mark4
#PBS -A hpc_herp01
#PBS -e picard_mark4.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN1312-aln_RG.bam O=popgen/6_picard/Pserratus_CEN1312-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN1312.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN132-aln_RG.bam O=popgen/6_picard/Pserratus_CEN132-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN132.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN134-aln_RG.bam O=popgen/6_picard/Pserratus_CEN134-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN134.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN136-aln_RG.bam O=popgen/6_picard/Pserratus_CEN136-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN136.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN139-aln_RG.bam O=popgen/6_picard/Pserratus_CEN139-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN139.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_CEN142-aln_RG.bam O=popgen/6_picard/Pserratus_CEN142-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_CEN142.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_ENR0165-aln_RG.bam O=popgen/6_picard/Pserratus_ENR0165-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_ENR0165.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_FHSM15253-aln_RG.bam O=popgen/6_picard/Pserratus_FHSM15253-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_FHSM15253.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_FHSM15535-aln_RG.bam O=popgen/6_picard/Pserratus_FHSM15535-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_FHSM15535.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_FHSM15547-aln_RG.bam O=popgen/6_picard/Pserratus_FHSM15547-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_FHSM15547.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_FHSM15548-aln_RG.bam O=popgen/6_picard/Pserratus_FHSM15548-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_FHSM15548.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_FHSM15549-aln_RG.bam O=popgen/6_picard/Pserratus_FHSM15549-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_FHSM15549.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ18827-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ18827-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ18827.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ18828-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ18828-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ18828.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ21037-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ21037-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ21037.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ21256-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ21256-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ21256.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ2558-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ2558-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ2558.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ2568-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ2568-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ2568.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_LSUMZ2569-aln_RG.bam O=popgen/6_picard/Pserratus_LSUMZ2569-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_LSUMZ2569.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_MVZ145058-aln_RG.bam O=popgen/6_picard/Pserratus_MVZ145058-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_MVZ145058.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_MVZ145059-aln_RG.bam O=popgen/6_picard/Pserratus_MVZ145059-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_MVZ145059.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_OMNH40315-aln_RG.bam O=popgen/6_picard/Pserratus_OMNH40315-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_OMNH40315.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false
java -Xmx2g -jar ~/anaconda/jar/MarkDuplicates.jar I=popgen/6_picard/Pserratus_OMNH41642-aln_RG.bam O=popgen/6_picard/Pserratus_OMNH41642-aln_MD.bam METRICS_FILE=popgen/6_picard/Pserratus_OMNH41642.metrics MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=250 ASSUME_SORTED=true REMOVE_DUPLICATES=false

date

exit 0