#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=4
#PBS -l walltime=1:00:00
#PBS -o for_faststructure.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N for_faststructure
#PBS -A hpc_herp01
#PBS -e for_faststructure.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

python $HOME_DIR/programs/faststructure_from_vcf_mod.py popgen/8_gatk/Pserratus_SNPs_phased.vcf popgen/structure/ Pserratus --first

date

exit 0
