#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o align_ebsp.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N align
#PBS -A hpc_herp01
#PBS -e align_ebsp.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata
cd $WORK_DIR

/home/cenewman/anaconda/bin/phyluce_align_seqcap_align --fasta matched_contigs/ebsp/ebsp.fasta --output matched_contigs/ebsp/mafft-nexus --taxa 17 --aligner mafft --cores 16

date

exit 0
