#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=12:00:00
#PBS -o phyluce_cull80.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N phyluce_cull80
#PBS -A hpc_herp01
#PBS -e phyluce_cull80.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/matched_contigs/taxon-set600/
cd $WORK_DIR

/home/cenewman/anaconda/bin/phyluce_align_get_only_loci_with_min_taxa --alignments mafft-nexus-clean/ --taxa 75 --percent 0.80 --output mafft-nexus-80 --cores 16

date

exit 0
