ozark.dm <- enmtools.dm(ozark, env, test.prop = 0.2)
appalachian.dm <- enmtools.dm(appalachian, env, test.prop = 0.2)
ouachita.dm <- enmtools.dm(ouachita, env, test.prop = 0.2)
louisiana.dm <- enmtools.dm(louisiana, env, test.prop = 0.2)
ozark.bc <- enmtools.bc(ozark, env, test.prop = 0.2)
appalachian.bc <- enmtools.bc(appalachian, env, test.prop = 0.2)
ouachita.bc <- enmtools.bc(ouachita, env, test.prop = 0.2)
louisiana.bc <- enmtools.bc(louisiana, env, test.prop = 0.2)
ouachita.glm <- enmtools.glm(f = pres ~ layer.1 + layer.2 + layer.3 + layer.4 + layer.5 + layer.6 + layer.7 + layer.8 + layer.9 + layer.10 + layer.11, species = ouachita, env = env, test.prop = 0.2)
louisiana.glm <- enmtools.glm(f = pres ~ layer.1 + layer.2 + layer.3 + layer.4 + layer.5 + layer.6 + layer.7 + layer.8 + layer.9 + layer.10 + layer.11, species = louisiana, env = env, test.prop = 0.2)
appalachian.mx <- enmtools.maxent(appalachian, env, test.prop = 0.2)
ouachita.mx <- enmtools.maxent(ouachita, env, test.prop = 0.2)
louisiana.mx <- enmtools.maxent(louisiana, env, test.prop = 0.2)
