app.mx.plot618_smpts <- visualize.enm.mod(app.mx, env, nbins = 500, layers=c("bio6","bio18"), plot.points = TRUE)
app.mx.plot184_smpts <- visualize.enm.mod(app.mx, env, nbins = 500, layers=c("bio18","bio4"), plot.points = TRUE)
pdf(file="pics/app_mx_6_18_suit.pdf")
app.mx.plot618_smpts$suit.plot + xlim(c(-150,100)) + ylim(c(100,665)) + ggtitle(label = "Appalachians: predicted suitability in env space (Maxent)")
dev.off()
pdf(file="pics/app_mx_6_18_bkgnd.pdf")
app.mx.plot618_smpts$background.plot + xlim(c(-150,100)) + ylim(c(100,665)) + ggtitle(label = "Appalachians: presence points & bkgnd density in env space (Maxent)")
dev.off()
pdf(file="pics/app_mx_18_4_suit.pdf")
app.mx.plot184_smpts$suit.plot + xlim(c(100,600)) + ylim(c(6000,8500)) + ggtitle(label = "Appalachians: predicted suitability in env space (Maxent)")
dev.off()
pdf(file="pics/app_mx_18_4_bkgnd.pdf")
app.mx.plot184_smpts$background.plot + xlim(c(100,600)) + ylim(c(6000,8500)) + ggtitle(label = "Appalachians: presence points & bkgnd density in env space (Maxent)")
dev.off()
