#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00
#PBS -o trinity_coverage_test.out
#PBS -M cnewm15@tigers.lsu.edu
#PBS -m ae
#PBS -N trinity_coverage
#PBS -A hpc_herp01
#PBS -e trinity_coverage_test.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/
cd $WORK_DIR

/home/cenewman/anaconda/bin/phyluce_assembly_get_trinity_coverage --assemblies assemblies_test/ --assemblo-config phyluce_trinity.conf --cores 16 --subfolder split-adapter-quality-trimmed --clean

date

exit 0
