#!/bin/bash
#PBS -q checkpt
#PBS -l nodes=1:ppn=16
#PBS -l walltime=5:00:00
#PBS -o gzip5.out
#PBS -M cnewm15@lsu.edu
#PBS -m ae
#PBS -N gzip5
#PBS -A hpc_skink01
#PBS -e gzip5.err

export HOME_DIR=/home/cenewman
export WORK_DIR=/work/cenewman/rawdata/illumiprocessor/rawreads
cd $WORK_DIR

gzip -c C6RLYANXX_s6_1_RapidGenomics_92_SL107544.fastq > SL107544_L006_R1_065.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_60_SL107512.fastq > SL107512_L006_R1_066.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_33_SL107485.fastq > SL107485_L006_R1_067.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_53_SL107505.fastq > SL107505_L006_R1_068.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_46_SL107498.fastq > SL107498_L006_R1_069.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_26_SL107478.fastq > SL107478_L006_R1_070.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_51_SL107503.fastq > SL107503_L006_R1_071.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_66_SL107518.fastq > SL107518_L006_R1_072.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_84_SL107536.fastq > SL107536_L006_R1_073.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_12_SL107464.fastq > SL107464_L006_R1_074.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_22_SL107474.fastq > SL107474_L006_R1_075.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_10_SL107462.fastq > SL107462_L006_R1_076.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_69_SL107521.fastq > SL107521_L006_R1_077.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_14_SL107466.fastq > SL107466_L006_R1_078.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_18_SL107470.fastq > SL107470_L006_R1_079.fastq.gz &
gzip -c C6RLYANXX_s6_1_RapidGenomics_68_SL107520.fastq > SL107520_L006_R1_080.fastq.gz &

wait


date

exit 0