#!/bin/bash
sed '1,3d; 6,66d' < Ambystoma_bishopi.txt > Ambystoma_bishopi_ext.txt
sed '1,3d; 6,66d' < Ambystoma_cingulatum.txt > Ambystoma_cingulatum_ext.txt
sed '1,3d; 6,66d' < Ambystoma_jeffersonianum.txt > Ambystoma_jeffersonianum_ext.txt
sed '1,3d; 6,66d' < Ambystoma_mabeei.txt > Ambystoma_mabeei_ext.txt
sed '1,3d; 6,66d' < Ambystoma_maculatum.txt > Ambystoma_maculatum_ext.txt
sed '1,3d; 6,66d' < Ambystoma_opacum.txt > Ambystoma_opacum_ext.txt
sed '1,3d; 6,66d' < Ambystoma_texanum.txt > Ambystoma_texanum_ext.txt
sed '1,3d; 6,66d' < Ambystoma_tigrinum.txt > Ambystoma_tigrinum_ext.txt
sed '1,3d; 6,66d' < Amphiuma_means.txt > Amphiuma_means_ext.txt
sed '1,3d; 6,66d' < Amphiuma_tridactylum.txt > Amphiuma_tridactylum_ext.txt
sed '1,3d; 6,66d' < Desmognathus_abditus.txt > Desmognathus_abditus_ext.txt
sed '1,3d; 6,66d' < Desmognathus_auriculatus.txt > Desmognathus_auriculatus_ext.txt
sed '1,3d; 6,66d' < Desmognathus_carolinensis.txt > Desmognathus_carolinensis_ext.txt
sed '1,3d; 6,66d' < Desmognathus_folkertsi.txt > Desmognathus_folkertsi_ext.txt
sed '1,3d; 6,66d' < Desmognathus_imitator.txt > Desmognathus_imitator_ext.txt
sed '1,3d; 6,66d' < Desmognathus_marmoratus.txt > Desmognathus_marmoratus_ext.txt
sed '1,3d; 6,66d' < Desmognathus_orestes.txt > Desmognathus_orestes_ext.txt
sed '1,3d; 6,66d' < Desmognathus_quadramaculatus.txt > Desmognathus_quadramaculatus_ext.txt
sed '1,3d; 6,66d' < Desmognathus_santeetlah.txt > Desmognathus_santeetlah_ext.txt
sed '1,3d; 6,66d' < Desmognathus_welteri.txt > Desmognathus_welteri_ext.txt
sed '1,3d; 6,66d' < Desmognathus_wrighti.txt > Desmognathus_wrighti_ext.txt
sed '1,3d; 6,66d' < Eurycea_bislineata.txt > Eurycea_bislineata_ext.txt
sed '1,3d; 6,66d' < Eurycea_cirrigera.txt > Eurycea_cirrigera_ext.txt
sed '1,3d; 6,66d' < Eurycea_guttolineata.txt > Eurycea_guttolineata_ext.txt
sed '1,3d; 6,66d' < Eurycea_junaluska.txt > Eurycea_junaluska_ext.txt
sed '1,3d; 6,66d' < Eurycea_longicauda.txt > Eurycea_longicauda_ext.txt
sed '1,3d; 6,66d' < Eurycea_lucifuga.txt > Eurycea_lucifuga_ext.txt
sed '1,3d; 6,66d' < Eurycea_quadridigitata.txt > Eurycea_quadridigitata_ext.txt
sed '1,3d; 6,66d' < Eurycea_wilderae.txt > Eurycea_wilderae_ext.txt
sed '1,3d; 6,66d' < Gyrinophilus_porphyriticus.txt > Gyrinophilus_porphyriticus_ext.txt
sed '1,3d; 6,66d' < Notophthalmus_viridescens.txt > Notophthalmus_viridescens_ext.txt
sed '1,3d; 6,66d' < Phaeognathus_hubrichti.txt > Phaeognathus_hubrichti_ext.txt
sed '1,3d; 6,66d' < Plethodon_amplus.txt > Plethodon_amplus_ext.txt
sed '1,3d; 6,66d' < Plethodon_angusticlavius.txt > Plethodon_angusticlavius_ext.txt
sed '1,3d; 6,66d' < Plethodon_aureolus.txt > Plethodon_aureolus_ext.txt
sed '1,3d; 6,66d' < Plethodon_cinereus.txt > Plethodon_cinereus_ext.txt
sed '1,3d; 6,66d' < Plethodon_cylindraceus.txt > Plethodon_cylindraceus_ext.txt
sed '1,3d; 6,66d' < Plethodon_electromorphus.txt > Plethodon_electromorphus_ext.txt
sed '1,3d; 6,66d' < Plethodon_glutinosus.txt > Plethodon_glutinosus_ext.txt
sed '1,3d; 6,66d' < Plethodon_hoffmani.txt > Plethodon_hoffmani_ext.txt
sed '1,3d; 6,66d' < Plethodon_hubrichti.txt > Plethodon_hubrichti_ext.txt
sed '1,3d; 6,66d' < Plethodon_jordani.txt > Plethodon_jordani_ext.txt
sed '1,3d; 6,66d' < Plethodon_kentucki.txt > Plethodon_kentucki_ext.txt
sed '1,3d; 6,66d' < Plethodon_meridianus.txt > Plethodon_meridianus_ext.txt
sed '1,3d; 6,66d' < Plethodon_metcalfi.txt > Plethodon_metcalfi_ext.txt
sed '1,3d; 6,66d' < Plethodon_montanus.txt > Plethodon_montanus_ext.txt
sed '1,3d; 6,66d' < Plethodon_petraeus.txt > Plethodon_petraeus_ext.txt
sed '1,3d; 6,66d' < Plethodon_punctatus.txt > Plethodon_punctatus_ext.txt
sed '1,3d; 6,66d' < Plethodon_richmondi.txt > Plethodon_richmondi_ext.txt
sed '1,3d; 6,66d' < Plethodon_sherando.txt > Plethodon_sherando_ext.txt
sed '1,3d; 6,66d' < Plethodon_shermani.txt > Plethodon_shermani_ext.txt
sed '1,3d; 6,66d' < Plethodon_virginia.txt > Plethodon_virginia_ext.txt
sed '1,3d; 6,66d' < Plethodon_yonahlossee.txt > Plethodon_yonahlossee_ext.txt
sed '1,3d; 6,66d' < Pseudotriton_ruber.txt > Pseudotriton_ruber_ext.txt
sed '1,3d; 6,66d' < Stereochilus_marginatus.txt > Stereochilus_marginatus_ext.txt
