a <- summary(Abarbouri_prj)
capture.output(a, file="Abarbouri.txt")
a <- summary(Atalpoideum_prj)
capture.output(a, file="Atalpoideum.txt")
a <- summary(Aaeneus_prj)
capture.output(a, file="Aaeneus.txt")
a <- summary(Daeneus_prj)
capture.output(a, file="Daeneus.txt")
a <- summary(Dfuscus_prj)
capture.output(a, file="Dfuscus.txt")
a <- summary(Dmonticola_prj)
capture.output(a, file="Dmonticola.txt")
a <- summary(Dochrophaeus_prj)
capture.output(a, file="Dochrophaeus.txt")
a <- summary(Docoee_prj)
capture.output(a, file="Docoee.txt")
a <- summary(Hscutatum_prj)
capture.output(a, file="Hscutatum.txt")
a <- summary(Pwehrlei_prj)
capture.output(a, file="Pwehrlei.txt")
a <- summary(Pwelleri_prj)
capture.output(a, file="Pwelleri.txt")
a <- summary(Pmontanus_prj)
capture.output(a, file="Pmontanus.txt")
