a <- summary(Ambystoma_jeffersonianum_prj)
capture.output(a, file="Ambystoma_jeffersonianum.txt")
a <- summary(Ambystoma_mabeei_prj)
capture.output(a, file="Ambystoma_mabeei.txt")
a <- summary(Ambystoma_maculatum_prj)
capture.output(a, file="Ambystoma_maculatum.txt")
a <- summary(Ambystoma_opacum_prj)
capture.output(a, file="Ambystoma_opacum.txt")
a <- summary(Ambystoma_texanum_prj)
capture.output(a, file="Ambystoma_texanum.txt")
a <- summary(Ambystoma_tigrinum_prj)
capture.output(a, file="Ambystoma_tigrinum.txt")
a <- summary(Amphiuma_means_prj)
capture.output(a, file="Amphiuma_means.txt")
a <- summary(Amphiuma_tridactylum_prj)
capture.output(a, file="Amphiuma_tridactylum.txt")
a <- summary(Desmognathus_abditus_prj)
capture.output(a, file="Desmognathus_abditus.txt")
a <- summary(Desmognathus_auriculatus_prj)
capture.output(a, file="Desmognathus_auriculatus.txt")
a <- summary(Desmognathus_carolinensis_prj)
capture.output(a, file="Desmognathus_carolinensis.txt")
a <- summary(Desmognathus_folkertsi_prj)
capture.output(a, file="Desmognathus_folkertsi.txt")
a <- summary(Desmognathus_imitator_prj)
capture.output(a, file="Desmognathus_imitator.txt")
a <- summary(Desmognathus_marmoratus_prj)
capture.output(a, file="Desmognathus_marmoratus.txt")
a <- summary(Desmognathus_orestes_prj)
capture.output(a, file="Desmognathus_orestes.txt")
a <- summary(Desmognathus_quadramaculatus_prj)
capture.output(a, file="Desmognathus_quadramaculatus.txt")
a <- summary(Desmognathus_santeetlah_prj)
capture.output(a, file="Desmognathus_santeetlah.txt")
a <- summary(Desmognathus_welteri_prj)
capture.output(a, file="Desmognathus_welteri.txt")
a <- summary(Desmognathus_wrighti_prj)
capture.output(a, file="Desmognathus_wrighti.txt")
a <- summary(Eurycea_bislineata_prj)
capture.output(a, file="Eurycea_bislineata.txt")
a <- summary(Eurycea_cirrigera_prj)
capture.output(a, file="Eurycea_cirrigera.txt")
a <- summary(Eurycea_guttolineata_prj)
capture.output(a, file="Eurycea_guttolineata.txt")
a <- summary(Eurycea_junaluska_prj)
capture.output(a, file="Eurycea_junaluska.txt")
a <- summary(Eurycea_longicauda_prj)
capture.output(a, file="Eurycea_longicauda.txt")
a <- summary(Eurycea_lucifuga_prj)
capture.output(a, file="Eurycea_lucifuga.txt")
a <- summary(Eurycea_quadridigitata_prj)
capture.output(a, file="Eurycea_quadridigitata.txt")
a <- summary(Eurycea_wilderae_prj)
capture.output(a, file="Eurycea_wilderae.txt")
a <- summary(Gyrinophilus_porphyriticus_prj)
capture.output(a, file="Gyrinophilus_porphyriticus.txt")
a <- summary(Notophthalmus_viridescens_prj)
capture.output(a, file="Notophthalmus_viridescens.txt")
a <- summary(Phaeognathus_hubrichti_prj)
capture.output(a, file="Phaeognathus_hubrichti.txt")
a <- summary(Plethodon_amplus_prj)
capture.output(a, file="Plethodon_amplus.txt")
a <- summary(Plethodon_angusticlavius_prj)
capture.output(a, file="Plethodon_angusticlavius.txt")
a <- summary(Plethodon_aureolus_prj)
capture.output(a, file="Plethodon_aureolus.txt")
a <- summary(Plethodon_cinereus_prj)
capture.output(a, file="Plethodon_cinereus.txt")
a <- summary(Plethodon_cylindraceus_prj)
capture.output(a, file="Plethodon_cylindraceus.txt")
a <- summary(Plethodon_electromorphus_prj)
capture.output(a, file="Plethodon_electromorphus.txt")
a <- summary(Plethodon_glutinosus_prj)
capture.output(a, file="Plethodon_glutinosus.txt")
a <- summary(Plethodon_hoffmani_prj)
capture.output(a, file="Plethodon_hoffmani.txt")
a <- summary(Plethodon_hubrichti_prj)
capture.output(a, file="Plethodon_hubrichti.txt")
a <- summary(Plethodon_jordani_prj)
capture.output(a, file="Plethodon_jordani.txt")
a <- summary(Plethodon_kentucki_prj)
capture.output(a, file="Plethodon_kentucki.txt")
a <- summary(Plethodon_meridianus_prj)
capture.output(a, file="Plethodon_meridianus.txt")
a <- summary(Plethodon_metcalfi_prj)
capture.output(a, file="Plethodon_metcalfi.txt")
a <- summary(Plethodon_montanus_prj)
capture.output(a, file="Plethodon_montanus.txt")
a <- summary(Plethodon_petraeus_prj)
capture.output(a, file="Plethodon_petraeus.txt")
a <- summary(Plethodon_punctatus_prj)
capture.output(a, file="Plethodon_punctatus.txt")
a <- summary(Plethodon_richmondi_prj)
capture.output(a, file="Plethodon_richmondi.txt")
a <- summary(Plethodon_sherando_prj)
capture.output(a, file="Plethodon_sherando.txt")
a <- summary(Plethodon_shermani_prj)
capture.output(a, file="Plethodon_shermani.txt")
a <- summary(Plethodon_virginia_prj)
capture.output(a, file="Plethodon_virginia.txt")
a <- summary(Plethodon_yonahlossee_prj)
capture.output(a, file="Plethodon_yonahlossee.txt")
a <- summary(Pseudotriton_ruber_prj)
capture.output(a, file="Pseudotriton_ruber.txt")
a <- summary(Stereochilus_marginatus_prj)
capture.output(a, file="Stereochilus_marginatus.txt")
