mv cleaned1/LSUMZ1928/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ1928/split-adapter-quality-trimmed/
mv cleaned1/LSUMZ1931/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ1931/split-adapter-quality-trimmed/
mv cleaned1/LSUMZ854/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ854/split-adapter-quality-trimmed/
mv cleaned2/LSUMZ18176/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18176/split-adapter-quality-trimmed/
mv cleaned2/LSUMZ2074/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ2074/split-adapter-quality-trimmed/
mv cleaned2/LSUMZ2199/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ2199/split-adapter-quality-trimmed/
mv cleaned2/LSUMZ2534/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ2534/split-adapter-quality-trimmed/
mv cleaned3/LSUMZ18530/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18530/split-adapter-quality-trimmed/
mv cleaned3/LSUMZ18531/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18531/split-adapter-quality-trimmed/
mv cleaned3/LSUMZ18772/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18772/split-adapter-quality-trimmed/
mv cleaned3/LSUMZ18817/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18817/split-adapter-quality-trimmed/
mv cleaned4/LSUMZ18818/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18818/split-adapter-quality-trimmed/
mv cleaned4/LSUMZ18820/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18820/split-adapter-quality-trimmed/
mv cleaned4/LSUMZ18878/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ18878/split-adapter-quality-trimmed/
mv cleaned4/LSUMZ19190/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ19190/split-adapter-quality-trimmed/
mv cleaned5/LSUMZ21030/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/LSUMZ21030/split-adapter-quality-trimmed/
mv cleaned5/OMNH2/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/OMNH2/split-adapter-quality-trimmed/
mv cleaned5/OMNH3/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/OMNH3/split-adapter-quality-trimmed/
mv cleaned5/OMNH4/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/OMNH4/split-adapter-quality-trimmed/
mv cleaned6/UAHC15971/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/UAHC15971/split-adapter-quality-trimmed/
mv cleaned6/UAHC15975/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/UAHC15975/split-adapter-quality-trimmed/
mv cleaned6/UAHC15978/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/UAHC15978/split-adapter-quality-trimmed/
mv cleaned6/UAHC16006/split-adapter-quality-trimmed/* cleaned_reads_from_illumiprocessor/UAHC16006/split-adapter-quality-trimmed/
