grep 'uce-1003' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1005' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-101' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1014' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1018' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1021' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-103' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1034' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1036' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1037' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1038' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1041' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1051' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1052' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1053' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1054' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1055' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1056' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1059' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1061' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1062' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1065' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1068' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1070' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1077' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1092' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1093' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1098' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-110' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1101' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1110' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1119' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1120' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1121' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1127' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1128' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1131' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1133' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1138' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1143' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1148' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-115' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1154' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1159' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1161' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1162' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-117' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1172' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1176' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1183' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1187' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-119' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1190' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1194' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-12' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-120' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1201' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1202' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1203' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1205' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-121' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1210' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1216' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1225' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1233' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1245' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1250' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1257' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1263' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1268' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-127' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1271' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1272' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1278' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1285' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-129' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1298' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1299' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1305' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1306' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1311' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1318' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1324' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1333' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1336' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1339' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-134' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1342' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1348' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1350' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1357' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1358' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1368' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1376' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1390' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1393' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1394' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1405' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1408' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1413' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1415' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1417' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-142' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1420' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1423' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1424' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1425' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1427' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1430' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1446' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1447' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1450' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1456' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-146' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1469' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1470' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1474' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1477' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-148' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1480' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1482' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1484' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1485' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1488' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-149' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1492' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1499' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-15' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1500' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1504' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1511' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1514' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1523' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1526' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1528' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1540' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1545' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1555' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1558' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1560' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1561' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1563' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1566' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1579' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1582' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1586' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1588' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1590' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1591' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1598' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-16' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1600' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1606' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1611' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1613' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1621' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1622' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1629' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1633' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1634' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1642' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1649' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1652' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1660' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1677' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1678' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1679' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1683' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-169' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-170' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-171' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1718' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1719' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-172' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1723' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1733' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1736' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1741' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1742' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1744' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1751' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1753' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1758' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1762' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1765' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1766' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1774' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-178' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1787' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1793' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-180' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1800' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1804' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1806' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-181' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1813' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1819' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1820' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1824' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1835' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1841' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1842' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1845' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1846' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1849' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1850' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-186' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1878' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1879' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-188' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1888' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1889' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1892' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1895' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1897' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1898' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1900' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1904' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1908' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1909' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1910' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1915' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1920' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1941' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1956' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1960' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1964' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1967' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1970' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1975' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1976' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-198' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1985' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1989' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1997' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-1998' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2003' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2005' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2006' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2007' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2010' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2016' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2018' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-202' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2020' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2028' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2034' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2040' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2041' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2042' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2043' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2049' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-205' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2052' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2054' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2057' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2066' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2069' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2070' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2082' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2089' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2104' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2108' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2116' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2119' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2129' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2140' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2147' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2149' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2151' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2156' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2162' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2164' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2166' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2169' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2179' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2180' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-219' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2195' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2196' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-220' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2206' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2211' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2217' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2222' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-223' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2245' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2247' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2252' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2255' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2262' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-227' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2279' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2282' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-23' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2320' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2321' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2334' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2336' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2338' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2345' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2353' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2356' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2358' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2378' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-238' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2383' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2387' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-239' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2397' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-24' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2404' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2409' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-241' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-243' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2432' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2441' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2446' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2450' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2452' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2462' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2466' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2468' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2472' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2478' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2480' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-25' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2503' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2505' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2510' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2515' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2516' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2526' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2537' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2538' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2544' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2546' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-255' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2550' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2553' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-256' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2572' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2574' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2599' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2600' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2605' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2611' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2614' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2625' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-263' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2642' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2656' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-266' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2671' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2676' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-268' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2703' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2708' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2716' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2728' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2735' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2742' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2746' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2757' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-276' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-277' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2770' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2772' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-278' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2782' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2785' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2788' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2802' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2811' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2816' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2839' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2841' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2849' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2851' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2857' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-286' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2870' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2879' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-288' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2895' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2897' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2899' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-29' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2909' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-291' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2925' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2928' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2930' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2940' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2943' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2955' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2964' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2965' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-297' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2980' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2987' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-2994' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-300' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3011' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3013' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3018' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3020' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3025' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3043' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3046' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-305' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3058' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3061' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3069' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3078' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3097' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3114' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3122' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3135' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3139' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-314' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3154' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3156' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3160' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-317' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3177' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-318' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3181' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3186' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3187' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3196' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3211' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3213' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3215' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-322' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3224' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3244' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3246' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-325' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-326' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3267' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3277' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3279' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3297' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-330' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3302' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3310' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3317' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3318' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3320' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3329' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-333' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3330' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3331' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3340' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3345' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3349' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-335' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3352' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3368' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3373' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3381' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3383' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3384' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3392' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3394' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3400' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3406' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-342' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3421' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3425' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3427' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3429' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3436' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3448' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3463' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3465' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3470' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3475' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3479' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3482' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3483' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3484' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3493' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3500' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3515' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-352' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3520' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3528' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-353' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3530' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3542' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3550' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3554' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3560' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3570' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3571' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3581' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3583' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3602' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3606' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3609' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3610' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3616' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3658' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3659' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3661' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3669' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3671' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3681' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3688' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3693' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3698' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3699' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3702' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3703' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3715' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3724' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-373' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3733' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3738' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3752' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3764' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3765' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-378' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3806' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3807' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-381' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3817' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3823' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3824' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3830' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3836' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3837' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3853' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3856' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3859' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3861' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3862' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3884' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3893' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3894' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3903' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3905' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3907' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3909' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3912' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3913' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3917' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3918' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3919' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3929' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3934' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3937' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-394' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3940' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-396' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3969' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3976' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3978' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-398' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3981' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3987' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3990' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3992' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3995' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-3999' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4001' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4003' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-401' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4014' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4022' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4035' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4042' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4044' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4061' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4068' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4094' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4110' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4115' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4117' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4143' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-415' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4159' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-416' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4161' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4167' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-417' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4172' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4176' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4179' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4184' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-419' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4190' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4199' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4206' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4208' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-422' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4227' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4234' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4237' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4238' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-424' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4248' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4249' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4256' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4259' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4261' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4278' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4279' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4285' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4287' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4295' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4301' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4313' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4334' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4335' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4337' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4339' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4345' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4347' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4349' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4353' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4354' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-436' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4361' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-438' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4395' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4396' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4408' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4414' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-442' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4423' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4425' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4434' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4442' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4445' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-445' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4451' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4453' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4458' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4472' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4485' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-450' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4513' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4519' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4523' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4525' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4527' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4532' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4538' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-454' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4540' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4544' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4549' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4558' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-457' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4573' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4574' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4575' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-458' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4586' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4593' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-46' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4607' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4614' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4616' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4618' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-464' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4643' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4652' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4658' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4666' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4674' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4680' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4681' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4693' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4695' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4711' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4719' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-472' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4724' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4726' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4730' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4733' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4744' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4747' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4754' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4760' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4763' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4778' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4779' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-478' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4799' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4806' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4807' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4819' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4833' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4837' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4839' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4844' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4845' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4850' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4856' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4858' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4862' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4872' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4881' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4884' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4902' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4908' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4918' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-492' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-493' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4930' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4935' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4939' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-494' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4944' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4952' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-496' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4960' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4966' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4967' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4976' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4977' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4980' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4982' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-499' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4990' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-4993' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5005' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5008' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5013' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5016' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5022' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5038' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5042' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5052' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5055' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5076' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5077' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5083' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5101' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5107' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5108' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5110' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5120' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5123' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5125' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-513' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5142' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5147' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5158' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-516' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5165' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5166' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-517' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5172' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5185' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5188' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5192' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-520' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5200' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5211' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5214' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-522' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5221' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5250' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5256' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-526' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5260' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-527' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5272' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5286' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5288' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-529' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5292' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5294' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5300' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5311' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5313' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5316' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5340' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-535' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5357' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5361' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5366' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5369' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5377' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5383' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5385' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5396' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-54' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-540' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-541' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5411' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5426' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5433' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5443' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5450' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5456' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5464' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5473' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5479' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5493' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5495' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5497' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5500' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5508' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-551' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5510' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-553' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5538' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-554' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5551' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5557' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5562' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5565' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5579' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-558' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5581' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5584' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5597' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5629' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5634' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5635' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5636' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5638' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5639' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-564' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5646' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5653' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5677' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5683' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5684' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5689' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5700' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5702' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5704' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5709' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5713' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-575' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5752' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5755' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5757' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5761' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5779' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5786' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5796' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5797' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5803' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5804' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5806' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5811' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5818' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5829' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5836' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5846' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5852' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5869' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-587' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5871' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5872' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5873' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5880' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5901' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5904' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5905' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-591' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5915' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5916' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5917' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5924' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5925' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5927' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5932' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5943' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5951' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5952' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5961' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5968' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5972' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-5974' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-598' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6007' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6017' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-603' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6031' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6034' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6035' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6048' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6049' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6054' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6059' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6060' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6070' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6074' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6094' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-61' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-610' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6101' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6102' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6106' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6120' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-613' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6133' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6136' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6137' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6152' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6161' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6163' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6166' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6167' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6177' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6187' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6195' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-62' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6204' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6205' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6206' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6208' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6209' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6210' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6221' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-624' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6245' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6249' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6254' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6256' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6260' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6267' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-627' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6274' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6278' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6287' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-629' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6290' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6294' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6296' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6298' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-63' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6301' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6311' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6314' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6316' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6323' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6334' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6335' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6340' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6352' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6353' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6360' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6367' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-638' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6390' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6397' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6398' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6400' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6406' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6407' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6409' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-641' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6410' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-642' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6426' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6432' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6441' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6454' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6471' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6473' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6476' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6478' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-65' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6505' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6508' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6509' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6512' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-652' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6520' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6530' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6540' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6570' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6574' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6580' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6585' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6588' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6595' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-660' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6608' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6618' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6627' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6633' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6641' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6642' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6682' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6704' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6714' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6715' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6718' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6719' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-672' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6721' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6723' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6724' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6726' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6731' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6735' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-674' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6746' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6747' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6757' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6762' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6771' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6774' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-678' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6780' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6782' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-680' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6812' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6824' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6827' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6850' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-686' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6871' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6873' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6880' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6881' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6898' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6902' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6909' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6910' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-692' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6922' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6923' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-693' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6931' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6939' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6946' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-696' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6964' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6981' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6988' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-6990' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-700' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7011' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7014' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7028' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7032' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7048' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7053' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7063' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7064' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7069' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7077' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-708' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7081' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7082' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7083' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7091' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7095' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7102' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-711' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7117' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7118' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-712' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7136' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7144' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7145' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7146' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7164' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-717' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7171' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7173' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7190' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-720' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7209' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7211' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7215' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7218' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7229' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7234' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7236' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-724' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-725' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7257' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-726' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7265' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7266' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-727' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7283' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7288' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-729' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7292' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7309' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7328' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-734' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7344' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-735' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7358' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7363' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7369' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-737' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-738' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7392' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7409' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7414' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7415' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7421' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7429' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-744' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7453' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-747' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7479' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7483' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7487' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7489' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7491' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7494' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7504' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7510' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7515' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7518' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-752' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7521' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7522' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-753' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7532' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7535' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-754' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7540' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7541' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7542' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7546' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7559' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7560' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7563' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7567' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7574' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7586' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-76' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7616' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7617' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-762' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7623' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7637' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-764' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7642' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7647' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7648' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7649' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-765' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7652' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7665' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7669' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-767' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7673' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7691' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7695' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7703' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7708' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-771' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7710' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7724' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7726' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7727' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-773' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7748' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7755' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7763' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7768' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-778' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7786' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7797' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-780' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7804' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7806' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7817' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7823' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7824' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-783' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7833' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7836' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-784' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7841' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7843' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7854' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7857' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-788' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7888' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7892' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7897' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7903' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7906' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-791' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7914' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7923' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7928' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-794' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7941' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7949' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7958' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7977' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7981' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7983' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7991' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7994' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7997' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-7999' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-8009' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-8011' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-803' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-8034' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-810' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-814' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-818' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-819' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-823' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-826' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-83' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-831' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-833' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-838' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-85' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-850' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-865' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-868' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-872' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-882' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-885' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-887' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-888' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-889' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-902' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-907' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-908' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-912' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-915' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-93' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-931' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-937' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-938' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-95' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-953' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-955' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-956' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-958' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-962' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-971' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-987' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
grep 'uce-998' tetrapods-uce-5kv1_culled.fasta >> overlapping-uces.txt
